apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-app
spec:
  destination:
    namespace: defalut
    server: https://kubernetes.default.svc
  project: default
  source:
    path: mysql
    repoURL: https://github.com/YZ775/argo-cd-tutorial.git
    targetRevision: main
  syncPolicy:
    automated: {}