kind: Namespace
apiVersion: v1
metadata:
  name: mysql
  labels:
    name: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
          - name : MYSQL_DATABASE
            value : testdb
          - name : MYSQL_ROOT_PASSWORD
            value : test
        ports:
        - containerPort: 3306